upstream usuarios {
    server usuarios:3001;
}
upstream productos {
    server productos:3002;
}
upstream pagos {
    server pagos:3003;
}

server {
    listen 80;

    location /api/usuarios {
        proxy_pass http://usuarios;
    }

    location /api/productos {
        proxy_pass http://productos;
    }

    location /api/pagos {
        proxy_pass http://pagos;
    }

    location / {
        return 200 '{"mensaje": "Tienda Online - API Gateway activo"}';
        add_header Content-Type application/json;
    }
}
